### ISSUE TITLE
App doesn't start anymore without reachable dock

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#338]
**Expected behavior**
For development purposes the remote-software app can be compiled and run on Linux, macOS and Windows without an actual dock or outside the home network.

**Current behavior**
The app doesn't start anymore without a reachable dock on the same network. It is stuck at the spinning circle.

**Detailed description**
- Latest dev branch
- Tested on Linux, macOS, Windows

**Comment by martonborzak** [comment]
I think I have fixed this.

**Comment by ChristianRiedl** [comment]
I had a similar problem. Can you set a breakpoint in integration.cpp where "emit loadComplete()" should fire. I think the problem is there.

**Comment by martonborzak** [comment]
The problem was that the dock integration wouldn't emit the signal, because it was connected to the mdns service discovery signal.
I added a timer to timeout and emit the loadComplete() signal

**Comment by zehnm** [comment]
Unfortunately it's still not working if I disconnect the dock and reboot the remote.
- latest dev branch as of today (remote-software & integration plugins)
- WiFi connection of the remote works (ssh connection works)
- Soon after I connect the dock the spinning circle on the remote ends and the app finishes starting up

Further information from the logs:
After connecting the dock the following log sequence starts:

1. qml loadComplete (main.qml 265)
1. connection successful (homeassistant.cpp 168)
1. connection successful: "YIO-Dock-xxx"

It looks like the remote startup is still stuck waiting for a connect signal / confirmation of the dock integration.

**Comment by martonborzak** [comment]
Pushed an update to the dock integration.

**Comment by zehnm** [comment]
Working now!
